### ISSUE TITLE
Custom.scss is broken

### ISSUE THREAD

**Issue by iogbole** [rundocs/jekyll-rtd-theme#14]
Hi, one of the changes that were made yesterday broke the custom.scss feature. It no longer takes effect. Thanks.

**Comment by saowang** [comment]
https://github.com/rundocs/jekyll-rtd-theme/releases/tag/v0.1.9

- Change `_sass/custom.scss` to `_includes/assets/custom.scss`

thanks!

**Comment by iogbole** [comment]
thanks
