### ISSUE TITLE
The TOC has files listed first and directories listed post that

### ISSUE THREAD

**Issue by nachiappannk** [rundocs/jekyll-rtd-theme#16]
Currently In the table of content, the files are listed first and directories are listed after that.
This is not ideal. 
It would be if we can have the folders listed in the middle of files as defined by the sort order

**Comment by saowang** [comment]
Yes, this really needs improvement so far, but due to the loop nesting mechanism of the liquid language used in the jekyll template (not perfect), the include loop is needed to list subdirectories, but it will destroy the variables, I will try again

**Comment by saowang** [comment]
Have tried to use another algorithm to list directories and files, but it is still a problem with `include`. If possible, you can try https://github.com/rundocs/test 

Thanks
