### ISSUE TITLE
NavBar compressing in downloaded theme, different than on rundocs.io website

### ISSUE THREAD

**Issue by konika3** [rundocs/jekyll-rtd-theme#17]
Hi,

I'm creating Jekyll-based docs website for offline use (not hosted on GitHub). To get started, I created my Jekyll site basically as a mirror of the rundocs.io repository using the latest 1.1.0 release of jekyll-rtd-theme. When I run my version, the navigation on the left is compressed, and doesn't show the entire table of contents like it does on the rundocs.io website, and collapses unused sections. Showing the table of contents all at once is desirable. All of the config files and Gem files are identical to the rundocs.io repository.

Is this a difference in the CSS or JS with the repository? When I look at the source, it references the same CSS file from https://cdn.jsdelivr.net. 

Thank you :)

![2020-08-18_01-05-09](https://user-images.githubusercontent.com/69835702/90472943-a9df2300-e0ef-11ea-90f2-09b949137289.jpg)

**Comment by saowang** [comment]
Have received

**Comment by saowang** [comment]
For the branch display you can
```yml
github_metadata: false
```

**Comment by saowang** [comment]
The blue text called "caption", I guess you run `jekyll server` in root(/)
You can try:
```bash
cd docs/
make
make sever
```

**Comment by konika3** [comment]
Thank you!!

`github_metadata: false`

did not have an impact on anything, but running `jekyll server` from the docs folder made it work perfectly. Thanks again for making such an awesome theme :)
