### ISSUE TITLE
Impossible to use several Admonition Cards of the same type on the same page

### ISSUE THREAD

**Issue by DrongoX** [rundocs/jekyll-rtd-theme#18]
Hello!

**Reproducing**:
The issue is the same with any type of Admonition Card.
Just make a page containing several Admonition Cards of the same type.
Sorry, I have no idea how to insert a markdown in a markdown, so I made a screenshot just in case ^^'
https://www.dropbox.com/s/h9h3438uzlt6r4e/Screenshot%202020-08-18%20at%2017.56.49.png

**Expected behavior:** 
The site shows 2 blocks of type `note` with different text.

**Actual behavior:**
2nd (and all consequent) `note`(s) will have the same text as 1st one.
https://www.dropbox.com/s/6zqqux2qwnt98mo/Screenshot%202020-08-18%20at%2017.59.21.png

**Comment by saowang** [comment]
Have received

**Comment by saowang** [comment]
Thank you for your report, this is indeed a bug, it has been fixed now, it is recommended to use the latest version (`remote_theme`),
Preview effect: https://rundocs.github.io/jekyll-rtd-theme/test/admonitions.html

**Comment by DrongoX** [comment]
Hey, thanks for the reactivity. 

I've actually tried before posting here the remote version and it still didn't work. Probably I've done something wrong, I'll look into it.

Thanks for quick feedback

**Comment by DrongoX** [comment]
@saowang Thanks for the reactivity! Everything works fine now. Have a nice day.
