### ISSUE TITLE
Sidebar Title Not Clickable 

### ISSUE THREAD

**Issue by zhongxiang117** [rundocs/jekyll-rtd-theme#29]
For the automatically generated nested sidebar, the files are clickable, which means they can be clicked to referring to their correct document without any problems. However, the Folder Title bar is not clickable for their own path.

For example, if the generated sidebar is

- TEST DOCUMENT
  1. Markdown Elements
  2. Album Images

- THIS IS AN INCREDIBLY LONG CAPTION FOR A LONG MENU
  1. I'm folder1
    - file1
    - file2

Except Two title bar, `TEST DOCUMENT` & `THIS IS AN INCREDIBLY LONG CAPTION FOR A LONG MENU`, all others are clickable.

This is pretty odd when those Title bar can be accessed by **breadcrumbs**, but cannot be reached by its own path.

### Possible solution:

Inside the file `_includes/extend/toctree.liquid` line *11*, change it to:

`<p class="caption"><span class="caption-text"><a href="{{ dir.url | relative_url }}">{{ dir.title | default: dir.url }}</a></span></p>`

Correspondingly, to make it consistent, add the new CSS style in the file `_sass/jekyll-rtd-theme.scss`:

```
/* fix folder link, no performance changes on the original style*/

.wy-menu-vertical p.caption span a {
    color: #55a5d9;
    font-size: inherit;
    padding: 0px;
    display: inline;
    line-height: unset;
    text-decoration: inherit;
}
```

**Comment by saowang** [comment]
See the original theme: https://sphinx-rtd-theme.readthedocs.io

**Comment by saowang** [comment]
In view of the fact that the sidebar of the theme is generated through the file directory structure, this feature is indeed subject to negotiation

**Comment by zhongxiang117** [comment]
Since this package is the updates for the original theme, then why not add this useful feature?

If sidebar is its navigated, then it is no need to use `breadcrumbs.liquid` to generate topbars. 

If the folder can be accessed from the topbar, then why not add meaningful sidebar?

Thank you for your consideration!

**Comment by zhongxiang117** [comment]
This is the image to better explain:

[jekyll-rtd-theme-titlebar](https://github.com/zhongxiang117/codeDump/blob/master/imageTrashBin/jekyll-rtd-theme-titlebar-problem.png)


I suggest to add this feature, thank you~
