### ISSUE TITLE
fluid: true breaks the site's responsiveness 

### ISSUE THREAD

**Issue by iogbole** [rundocs/jekyll-rtd-theme#34]
Pages are not responsive if fluid: true.  This is what it looks like from a phone. 

 Is it possible to correct this at all? 

![Screenshot 2020-09-09 at 20 00 51](https://user-images.githubusercontent.com/2548160/92642135-ae09f500-f2d7-11ea-8540-3f104871cac8.png)

**Comment by saowang** [comment]
It’s been a long time since I saw this problem on your website. It should be caused by your custom css. Use it first, and the next refactored version will be ready soon.

**Comment by iogbole** [comment]
@saowang  you're referring to this CSS? If so, they are the default CSS except for the values of `background-color`

```
.wy-side-nav-search {
	display: block;
	width: 300px;
	padding: .809em;
	margin-bottom: .809em;
	z-index: 200;
	background-color: #271d6b;
	text-align: center;
	color: #fcfcfc
}

.wy-nav-side {
	position: fixed;
	top: 0;
	bottom: 0;
	left: 0;
	padding-bottom: 2em;
	width: 300px;
	overflow-x: hidden;
	overflow-y: hidden;
	min-height: 100%;
	color: #9b9b9b;
	background: #271d6b;
	z-index: 200
}
```

**Comment by saowang** [comment]
cdn.jsdelivr.net is down!

check: https://cdn.jsdelivr.net/gh/rundocs/jekyll-rtd-theme@1.1.7/assets/css/theme.css

**Comment by iogbole** [comment]
Thank you, @saowang . Solved.
