### ISSUE TITLE
Search feature is not working 

### ISSUE THREAD

**Issue by ceesuade** [rundocs/jekyll-rtd-theme#38]
**Describe the bug**
When you perform a search it does not return any results.  This is the main feature of the template but only pulls back blank results.  Just forked most recent files and can reproduce the issue.

**To Reproduce**
Steps to reproduce the behavior: Try searching for anything and no results are displayed 

**Expected behavior**
To see results of what the user is searching for

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: Win10
- Browser chrome
- Version 85.0.4183.102 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: multiple devices tried all produce the same a blank page when searching

**Additional context**
LOVE the template great work just need to get the main feature working again :)

**Comment by saowang** [comment]
Thank you, the official version will be released in the next few days during the 2.0 public beta

**Comment by saowang** [comment]
use old version:

remote_theme: rundocs/jekyll-rtd-theme@v1.1.7

**Comment by ceesuade** [comment]
TY so much for the prompt reply and GREAT work.  Will there be a way I can get the search feature working without effecting the current chanages I have been building my site out with ?  IE mostly css changes plus my own .md files.  

 

When released could you point me the right direction of what files I need to use to get things working or best path forward.  Many thanks again and keep up the GREAT work !!!
