### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ceesuade** [rundocs/jekyll-rtd-theme#40]
AWESOME work fixing the search !!!! 👏

With the latest build i now have a issue with the CSS all of my css changes local are not getting called and it actually is going out and pull cdn.jsdelivr.net :( i have updated the CSS in the theme but it never gets called now.

How can i get around it calling the cdn.jsdelivr.net to pull in the css and js ? my color is set to b06cb1 for the background however you can see in the screenshot it is never getting called :( 

![image](https://user-images.githubusercontent.com/19297048/93815085-6e220680-fc23-11ea-845f-9eae026f0085.png)

**Comment by saowang** [comment]
#34 #39

**Comment by saowang** [comment]
Have fixed! you may need update your scss code, because 2.0 have refactored the origin theme!

**Comment by saowang** [comment]
```
remote_theme: rundocs/jekyll-rtd-theme@v1
```
