### ISSUE TITLE
Breadcrumbs showing filename instead of title

### ISSUE THREAD

**Issue by eluinstra** [rundocs/jekyll-rtd-theme#41]
The breadcrumbs are showing the filename instead of the title defined in the file.

Open a page and see that the breadcrumbs contains the filename

For example on your own test site when opening https://jekyll-rtd-theme.rundocs.io/test/markdown.html, the breadcrumbs show /test/markdown.md instead of /test/Markdown Elements.
This was working fine in version 1.1.7.

Btw, I really like the theme.

**Comment by saowang** [comment]
I also changed this after careful consideration. I think that combined with the edit button on the right can clearly know which file is being edited.

What do you think

**Comment by eluinstra** [comment]
ok, that's the reason. So when I disable the edit button, the title will show again?

**Comment by saowang** [comment]
No, the editing option is obsolete. The edit button must be used for open source project documents. Please submit a pull request for any improvement!

**Comment by eluinstra** [comment]
Oh, that's a pity. I think the breadcrumbs should be readable for the reader and not the editor, but that is just my opinion.

Thanks again for providing this nice theme.

**Comment by ceesuade** [comment]
I agree I think it should be shown from a viewers point of view on the front end it means more to a user.  If you are editing files you should be familiar with where things are on the back end and how the documents relate.  Great work and theme you been busy keep it up !  Just my opnion too kind of like you never show IDs through in the front end as it means nothing except if your a dev :) I get your thinking just feel the Title would be more helpful to the end user :)
