### ISSUE TITLE
Analytics behind a flag

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [rundocs/jekyll-rtd-theme#49]
**Describe the BUG**
Version 1 had analytics as an add-on. There doesn't seem to be an easy way to turn them off anymore.

I'd like to not send all my users data to some external site I don't control.

For now I'll probably rip the relevant code out of the javascript [here](https://github.com/rundocs/jekyll-rtd-theme/blob/master/assets/js/theme.js#L289-L292)

**Comment by saowang** [comment]
No, you don’t need it if you don’t like it, maybe some adjustments will be made in the future according to the github API of the project, thank you
