### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by ylqi007** [rundocs/jekyll-rtd-theme#57]
Hi, beautiful theme.
I’m a newbie to JekyII, is there any documentation that can guide how to create a Github page with this theme?

Sincerely

**Comment by saowang** [comment]
Start from: https://github.com/rundocs/starter-slim or https://github.com/rundocs/starter
Sidebar see: https://rundocs.io/configuring/sidebar.html

**Comment by ylqi76207** [comment]
@saowang Is there any instruction about how to post a new page?

Sincerely

**Comment by ylqi007** [comment]
I tried to use this theme follwoing [Installing a gem-based theme](https://jekyllrb.com/docs/themes/#installing-a-theme) from scratch, I got the following error. I tried to locate `github_edit_link` but I cannot get it. Could you please help me solve this?

```
Liquid Exception: Liquid syntax error (/home/xxxxx/gems/gems/jekyll-rtd-theme-2.0.8/_includes/class/content-wrap.liquid line 30): Unknown tag 'github_edit_link' included in /_layouts/default.liquid
jekyll 3.9.0 | Error:  Liquid syntax error (/home/xxxxx/gems/gems/jekyll-rtd-theme-2.0.8/_includes/class/content-wrap.liquid line 30): Unknown tag 'github_edit_link' included 
```

Sincerely

**Comment by saowang** [comment]
https://rundocs.io/configuring/gemfile.html

**Comment by saowang** [comment]
You need to add github-pages as plugins
