### ISSUE TITLE
Settings and search 

### ISSUE THREAD

**Issue by iogbole** [rundocs/jekyll-rtd-theme#7]
Hi is it possible to hide edit on github, the sidebar footer, please? 

Also, the search is not working

**Comment by saowang** [comment]
It is a good idea, I'll write it for you tommow when I wake up!

Search is woking, unless you do not have content, i guess.

Thanks

**Comment by iogbole** [comment]
Thanks, I can confirm that the search started working after ~3 hrs. I am using Github pages remote_themes so it may be slower. Regarding the sidebar footer, it will be great to make it configurable as I really don't want to show visitors and gem list. 
![Screenshot 2020-07-26 at 19 39 52](https://user-images.githubusercontent.com/2548160/88487069-09776200-cf7a-11ea-8001-eb6c33d2274d.png)

**Comment by saowang** [comment]
Now the foorer  of sidebar is default `false`
```yml
addons: false
```
if you want show any one of `GitHub`,`Gems`,`Statistics` do
```yml
addons:
  - github
  - gems
  - analytics
```

they follow the option order, you can
```yml
addons:
  - github
```

**Comment by saowang** [comment]
```yml
addons_commit: false # defualt
```
addons_commit is 
![addons_commit](https://user-images.githubusercontent.com/68011645/88498575-189bf580-cff6-11ea-8385-056a382c729f.png)
