### ISSUE TITLE
Latex equation notation does not render

### ISSUE THREAD

**Issue by spestana** [rundocs/jekyll-rtd-theme#81]
**Describe the BUG**

When adding the following latex notation equation: $\hat{B}1 \pm t{\frac{\alpha}{2},n-2} \cdot s_{B_1}$ it does not render and instead displays as normal text.

Would this be a feature that can be added to the theme?

**To Reproduce**

Add any latex notation to a page and commit to build the page.

**Site link or Repository**

https://github.com/spestana/data-analysis

**Comment by saowang** [comment]
Ok! tomorrow!

**Comment by saowang** [comment]
Now you can try this:

```
$$
\begin{aligned}
  & \phi(x,y) = \phi \left(\sum_{i=1}^n x_ie_i, \sum_{j=1}^n y_je_j \right)
  = \sum_{i=1}^n \sum_{j=1}^n x_i y_j \phi(e_i, e_j) = \\
  & (x_1, \ldots, x_n) \left( \begin{array}{ccc}
      \phi(e_1, e_1) & \cdots & \phi(e_1, e_n) \\
      \vdots & \ddots & \vdots \\
      \phi(e_n, e_1) & \cdots & \phi(e_n, e_n)
    \end{array} \right)
  \left( \begin{array}{c}
      y_1 \\
      \vdots \\
      y_n
    \end{array} \right)
\end{aligned}
$$
```

**Comment by spestana** [comment]
Thank you!
