### ISSUE TITLE
Side Nav and Search Box colour

### ISSUE THREAD

**Issue by iogbole** [rundocs/jekyll-rtd-theme#9]
I was wondering if it is possible to change the background colours of the side-nav and search box? 
I attempted this by overriding theme.css in my project but it didn't take effect - https://github.com/rundocs/jekyll-rtd-theme/blob/master/assets/css/theme.css

Would you consider adding a setting for this, considering it is very important to use custom branding colours? Thanks 

The target  CSS classes are: 

```
.wy-side-nav-search {
	display: block;
	width: 300px;
	padding: .809em;
	margin-bottom: .809em;
	z-index: 200;
	background-color: **#custom-colour-code**;
	text-align: center;
	color: #fcfcfc
}
```
and 

```
wy-nav-side {
	position: fixed;
	top: 0;
	bottom: 0;
	left: 0;
	padding-bottom: 2em;
	width: 300px;
	overflow-x: hidden;
	overflow-y: hidden;
	min-height: 100%;
	color: #9b9b9b;
	background: **#custom-colour-code**;
	z-index: 200
}

```

**Comment by saowang** [comment]
Received your issue!

**Comment by saowang** [comment]
## Now latest version theme avaiable!

Add your target CSS to `_sass/custom.scss`]

### Custom scss or script

```yml
_sass/custom.scss

_includes/assets/js/custom.js
```

Thanks a lot!

**Comment by iogbole** [comment]
Works great. Thank you for the quick response.
