### ISSUE TITLE
RFE: Allow configurable name in breadcrumb

### ISSUE THREAD

**Issue by iranzo** [rundocs/jekyll-rtd-theme#93]
Hi,
Actually breadcrumb is showing page.name, which might be cool but sometimes it's better to use page.title which can be defined in the frontmatter.

Would be nice to allow theme to be configurable to use one or the other (even defaulting to actual page.name).

**Comment by saowang** [comment]
In fact, considering this issue, the reasons for choosing to display the file name are: 1. You can better understand which file you are viewing, which is convenient for editing. 2. Generally, the title will appear on the page in a large font, and the same text will appear in the breadcrumbs. Seems redundant
