### ISSUE TITLE
using-with-github-enterprise

### ISSUE THREAD

**Issue by andre68723** [rundocs/jekyll-rtd-theme#95]
Hi,

theme works fine, however all links generated (e.g the edit button) always point to github.com

I followed http://jekyll.github.io/github-metadata/configuration/#using-with-github-enterprise
and set _config.yml properly (to my understanding)

```
repository: myorg/documentation
PAGES_API_URL: "https://api.github.my.corp"
PAGES_GITHUB_HOSTNAME: "https://github.my.corp/"
OCTOKIT_API_ENDPOINT: "https://api.github.my.corp"
OCTOKIT_WEB_ENDPOINT: "https://github.my.corp/"
PAGES_PAGES_HOSTNAME: "https://github.my.corp/pages/"
```

still all goes to github.com ☹️, edit or also the lower left menu with hp, issues, dl

**Comment by saowang** [comment]
Edit `_config.yml`:
```yml
repository: myorg/documentation
```

Run this:
```sh
PAGES_GITHUB_HOSTNAME=https://xxxxxxxxxxxxxx.com bundle exec jekyll server
```

Follow this: http://jekyll.github.io/github-metadata/configuration/#overrides
